import React, { useState } from "react";

export default function EmployerAiJobMatching() {
  // Sample job postings created by the employer (from `job_postings` ER table)
  const [selectedJobId, setSelectedJobId] = useState("JOB-101");

  const jobPostings = [
    {
      id: "JOB-101",
      title: "Frontend React Developer",
      department: "Engineering",
      requiredSkills: ["React", "JavaScript", "Tailwind CSS", "REST APIs"],
      experienceLevel: "Entry Level (0-2 Yrs)",
      openings: 3,
      location: "Pune, Maharashtra",
    },
    {
      id: "JOB-102",
      title: "Cloud Infrastructure Associate",
      department: "DevOps",
      requiredSkills: ["AWS", "Docker", "Linux", "CI/CD"],
      experienceLevel: "Junior Level (1-2 Yrs)",
      openings: 2,
      location: "Mumbai, Maharashtra",
    },
  ];

  // Matched candidate profiles generated by the AI Engine (from `job_matches` & `skill_passports` ER tables)
  const candidateMatches = [
    {
      matchId: "MATCH-9001",
      traineeId: "MH-2024-TR-84920",
      traineeName: "Rahul Patil",
      matchScore: 94,
      aiAnalysis: "Strong alignment in React and UI framework projects. Completed MSSDS Web Dev L1 Certification.",
      matchedSkills: ["React", "JavaScript", "Tailwind CSS"],
      missingSkills: ["REST APIs"],
      certificationVerified: true,
      experience: "1 Year Internship",
      jobId: "JOB-101",
      status: "Recommended",
    },
    {
      matchId: "MATCH-9002",
      traineeId: "MH-2024-TR-90112",
      traineeName: "Sneha Kulkarni",
      matchScore: 88,
      aiAnalysis: "Exceeds JavaScript requirements. Verified Skill Passport with 4 completed certifications.",
      matchedSkills: ["JavaScript", "REST APIs", "Tailwind CSS"],
      missingSkills: ["React"],
      certificationVerified: true,
      experience: "6 Months Project Experience",
      jobId: "JOB-101",
      status: "Shortlisted",
    },
    {
      matchId: "MATCH-9003",
      traineeId: "MH-2024-TR-76123",
      traineeName: "Amit Deshmukh",
      matchScore: 92,
      aiAnalysis: "High match score for AWS and Docker. Certified in MSSDS Cloud Deployment Essentials.",
      matchedSkills: ["AWS", "Linux", "Docker"],
      missingSkills: ["CI/CD"],
      certificationVerified: true,
      experience: "1 Year Apprentice",
      jobId: "JOB-102",
      status: "Recommended",
    },
  ];

  // Active Job Details
  const activeJob = jobPostings.find((job) => job.id === selectedJobId);

  // Filter candidate matches for the currently selected job posting
  const activeMatches = candidateMatches.filter(
    (candidate) => candidate.jobId === selectedJobId
  );

  return (
    <div className="min-h-screen bg-[#f0f4f9] p-6 space-y-6 font-sans text-[#0f172a]">
      
      {/* Header Banner */}
      <div className="bg-white p-6 rounded-2xl border border-[#e2e8f0] shadow-xs flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="inline-flex items-center space-x-2 bg-[#eef2ff] border border-[#c7d2fe] text-[#4338ca] text-[11px] font-bold px-3 py-1 rounded-full mb-2">
            <span className="w-2 h-2 rounded-full bg-[#4f46e5]"></span>
            <span>Feature • AI Candidate Matching Engine</span>
          </div>
          <h1 className="text-2xl font-black text-[#0f172a] tracking-tight">
            AI Job & Skill Matching
          </h1>
          <p className="text-xs text-[#64748b] font-medium mt-0.5">
            Automated candidate scoring connecting open positions with verified Trainee Skill Passports.
          </p>
        </div>

        {/* Job Posting Selector */}
        <div className="flex items-center space-x-3 shrink-0">
          <label className="text-xs font-bold text-[#64748b]">Active Job Opening:</label>
          <select
            value={selectedJobId}
            onChange={(e) => setSelectedJobId(e.target.value)}
            className="bg-[#f8fafc] border border-[#cbd5e1] text-[#0f172a] text-xs font-bold rounded-xl px-3.5 py-2.5 focus:outline-none focus:border-[#4f46e5]"
          >
            {jobPostings.map((job) => (
              <option key={job.id} value={job.id}>
                {job.title} ({job.department})
              </option>
            ))}
          </select>
        </div>
      </div>

      {/* Selected Job Profile Details */}
      {activeJob && (
        <div className="bg-white p-6 rounded-2xl border border-[#e2e8f0] shadow-xs space-y-4">
          <div className="flex flex-col md:flex-row md:items-center justify-between border-b border-[#f1f5f9] pb-3 gap-2">
            <div>
              <span className="text-[10px] font-mono text-[#64748b] bg-[#f1f5f9] px-2 py-0.5 rounded">
                {activeJob.id}
              </span>
              <h2 className="text-lg font-bold text-[#0f172a] mt-1">{activeJob.title}</h2>
            </div>
            <div className="flex items-center space-x-3 text-xs font-semibold text-[#64748b]">
              <span>📍 {activeJob.location}</span>
              <span>•</span>
              <span>👥 {activeJob.openings} Openings</span>
              <span>•</span>
              <span>💼 {activeJob.experienceLevel}</span>
            </div>
          </div>

          <div className="flex items-center space-x-2 text-xs">
            <span className="font-bold text-[#64748b]">Target Skills criteria:</span>
            <div className="flex flex-wrap gap-1.5">
              {activeJob.requiredSkills.map((skill, index) => (
                <span
                  key={index}
                  className="bg-[#eef2ff] text-[#4338ca] border border-[#c7d2fe] text-[11px] font-bold px-2.5 py-0.5 rounded-lg"
                >
                  {skill}
                </span>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Candidate Matches Section */}
      <div className="space-y-4">
        <h3 className="text-sm font-extrabold uppercase text-[#94a3b8] tracking-wider px-1">
          Top AI-Matched Candidates ({activeMatches.length})
        </h3>

        {activeMatches.map((candidate) => (
          <div
            key={candidate.matchId}
            className="bg-white p-6 rounded-2xl border border-[#e2e8f0] shadow-xs space-y-4 hover:border-[#cbd5e1] transition-all"
          >
            {/* Top Bar: Trainee Name & AI Match Badge */}
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-[#f1f5f9] pb-3">
              <div className="flex items-center space-x-3">
                <div className="w-12 h-12 rounded-2xl bg-[#eef2ff] border border-[#c7d2fe] text-[#4f46e5] font-black text-base flex items-center justify-center">
                  {candidate.traineeName.charAt(0)}
                </div>
                <div>
                  <div className="flex items-center space-x-2">
                    <h4 className="text-base font-bold text-[#0f172a]">{candidate.traineeName}</h4>
                    {candidate.certificationVerified && (
                      <span className="bg-[#dcfce7] text-[#15803d] border border-[#bbf7d0] text-[10px] font-bold px-2 py-0.5 rounded-md">
                        ✓ Verified Passport
                      </span>
                    )}
                  </div>
                  <p className="text-xs text-[#64748b] font-mono mt-0.5">
                    ID: {candidate.traineeId} • Experience: {candidate.experience}
                  </p>
                </div>
              </div>

              {/* Match Percentage Badge */}
              <div className="flex items-center space-x-3">
                <div className="text-right">
                  <p className="text-[10px] font-extrabold text-[#94a3b8] uppercase">AI Match Score</p>
                  <p className="text-xl font-black text-[#4f46e5]">{candidate.matchScore}%</p>
                </div>
                <div className="w-12 h-12 rounded-2xl bg-[#4f46e5] text-white flex items-center justify-center text-sm font-black shadow-xs">
                  🎯
                </div>
              </div>
            </div>

            {/* AI Reasoning Analysis */}
            <div className="bg-[#f8fafc] p-3.5 rounded-xl border border-[#f1f5f9] text-xs space-y-1">
              <p className="font-bold text-[#0f172a] flex items-center space-x-1">
                <span>🤖</span>
                <span>AI Matching Insights:</span>
              </p>
              <p className="text-[#64748b] leading-relaxed">{candidate.aiAnalysis}</p>
            </div>

            {/* Skills Breakdown Grid */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 text-xs">
              <div className="space-y-1.5">
                <p className="font-bold text-[#15803d]">Matched Skills ({candidate.matchedSkills.length})</p>
                <div className="flex flex-wrap gap-1.5">
                  {candidate.matchedSkills.map((skill, i) => (
                    <span key={i} className="bg-[#dcfce7] text-[#15803d] border border-[#bbf7d0] text-[11px] font-bold px-2.5 py-0.5 rounded-md">
                      ✓ {skill}
                    </span>
                  ))}
                </div>
              </div>

              <div className="space-y-1.5">
                <p className="font-bold text-[#b91c1c]">Skill Gaps ({candidate.missingSkills.length})</p>
                <div className="flex flex-wrap gap-1.5">
                  {candidate.missingSkills.map((skill, i) => (
                    <span key={i} className="bg-[#fef2f2] text-[#b91c1c] border border-[#fecaca] text-[11px] font-bold px-2.5 py-0.5 rounded-md">
                      ✕ {skill}
                    </span>
                  ))}
                </div>
              </div>
            </div>

            {/* Action Bar */}
            <div className="flex items-center justify-end space-x-3 pt-2 border-t border-[#f1f5f9]">
              <button
                type="button"
                onClick={() => alert(`Viewed profile of ${candidate.traineeName}`)}
                className="px-4 py-2 rounded-xl border border-[#cbd5e1] text-[#475569] hover:bg-[#f8fafc] text-xs font-bold transition-all"
              >
                View Skill Passport
              </button>
              <button
                type="button"
                onClick={() => alert(`Shortlisted ${candidate.traineeName} for interview.`)}
                className="px-4 py-2 rounded-xl bg-[#4f46e5] hover:bg-[#4338ca] text-white text-xs font-bold transition-all shadow-xs"
              >
                Shortlist Candidate →
              </button>
            </div>

          </div>
        ))}
      </div>

    </div>
  );
}